In [1]:
#pandas와 numpy를 import 시킴
import numpy as np
import pandas as pd

## test yourself

* $ a = [1, 2, 3], b = [4, 5, 6] $일 때 배운 np 연산을 이용하여 32를 출력해보시오.
* 행렬연산을 이용해보시오.
* 산술연산을 이용해보시오.

In [2]:
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])

print(np.dot(a, b))
print(a@b)

[[32]]
[[32]]


$$\begin{pmatrix} 5 & 2 & 5 \\ 1 & 7 & 4 \\ -4 & 8 & 5 \end{pmatrix}$$
* 주어진 (1) 행렬의 값을 5배 키워보시오.

In [3]:
matrix_1 = np.array([[5, 2, 5],
                   [1, 7, 4],
                   [-4, 8, 5]])

print(matrix_1 * 5)

[[ 25  10  25]
 [  5  35  20]
 [-20  40  25]]


* 주어진 (1) 3x3 행렬에서 axis 1와 axis 2으로 sum을 한 각각의 결과를 서로 product하여 scalar값을 출력해보시오.

In [4]:
sum_axis_0 = np.sum(matrix_1, axis=0)
sum_axis_1 = np.sum(matrix_1, axis=1)

scalar_result = np.prod([np.prod(sum_axis_0), np.prod(sum_axis_1)])

print(scalar_result)

616896


## test yourself

In [5]:
df = pd.read_csv('./titanic.csv')
df.head(10)

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   
5         0       3                                    Mr. James Moran   
6         0       1                             Mr. Timothy J McCarthy   
7         0       3                      Master. Gosta Leonard Palsson   
8         1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500  
5    male  27.0                        0                        0   8.4583  
6    male  54.0                        0                        0  51.8625  
7    male   2.0                        3                        1  21.0750  
8  female  27.0                        0                        2  11.1333  
9  female  14.0                        1                        0  30.0708

* 주어진 타이타닉 사고 데이터를 이용하여 남성/여성의 총 인원수를 집계해보시오

In [6]:
df['Sex'].value_counts()

Sex
male      573
female    314
Name: count, dtype: int64

* 주어진 타이타닉 데이터에서 생존 남성의 평균 연령, 생존 여성의 평균 연령을 산출해보시오.

In [7]:
survived_male = df[(df['Survived'] == 1) & (df['Sex'] == 'male')]
survived_male_avg_age = survived_male['Age'].mean().astype(int)

survived_female = df[(df['Survived'] == 1) & (df['Sex'] == 'female')]
survived_female_avg_age = survived_female['Age'].mean().astype(int)

print("생존 남성의 평균 연령 :", survived_male_avg_age)
print("생존 여성의 평균 연령 :", survived_female_avg_age)

생존 남성의 평균 연령 : 27
생존 여성의 평균 연령 : 28


* 타이타닉 사고 데이터에서 남성의 생존률과 여성의 생존률을 Pclass 대비로 측정해 보시오

In [8]:
survival_counts = df.groupby(['Sex', 'Pclass'])['Survived'].mean()

print("남성과 여성의 Pclass 대비 생존률 :\n", survival_counts)

남성과 여성의 Pclass 대비 생존률 :
 Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.137026
Name: Survived, dtype: float64
